import { Unit } from '../../../game/Unit/Unit';
import { UnitAi } from '../../../game/Unit/UnitAi';
import { ActionType } from '../../../game/Unit/UnitAction';
import { ReactionSystem } from '../../../game/Unit/Combat/ReactionSystem';
import { AttackResolver } from '../../../game/Unit/Combat/AttackResolver';
import { events, GameEvent } from '../../../game/events';

/**
 * UnitCombatAi implements autonomous combat behavior for units in battle scenarios
 * Each unit with this AI will:
 * - Detect nearby enemies autonomously
 * - Move toward enemies to engage
 * - Make combat decisions (attack/block/dodge)
 * - React to incoming attacks via event system
 * Single responsibility: Autonomous combat behavior for one unit
 */
export class UnitCombatAi implements UnitAi {
    /**
     * Reaction system handles detection and timing for defensive actions
     */
    private reactionSystem = new ReactionSystem();

    /**
     * Combat engagement range in pixels
     * Units stop moving and start fighting when within this distance
     */
    private combatRange = 50;

    /**
     * Current simulation time (seconds)
     * Used for reaction timing
     */
    private currentTime = 0;

    /**
     * Reference to all units in the battle
     * Set by BattleMode when initializing AI
     */
    private allUnits: Unit[] = [];

    /**
     * Combat messages generated by this unit's actions
     * Stored for logging/display purposes
     */
    private messages: string[] = [];

    /**
     * The unit this AI is controlling
     */
    private controlledUnit: Unit | null = null;

    /**
     * Sets the list of all units in battle
     * Called by BattleMode during initialization
     */
    setAllUnits(units: Unit[]) {
        this.allUnits = units;
    }

    /**
     * Gets combat messages generated by this unit
     */
    getMessages(): string[] {
        return this.messages;
    }

    /**
     * Clears combat messages
     */
    clearMessages() {
        this.messages = [];
    }

    /**
     * Resets AI state
     */
    reset() {
        this.currentTime = 0;
        this.messages = [];
        this.reactionSystem = new ReactionSystem();
    }

    /**
     * Updates autonomous combat behavior for this unit
     * @param unit - The unit this AI is controlling
     * @param deltaTime - Time elapsed since last update
     */
    update(unit: Unit, deltaTime: number) {
        this.currentTime += deltaTime;

        // Set up event listeners on first update
        if (!this.controlledUnit) {
            this.controlledUnit = unit;
            this.setupEventListeners();
        }

        // Can't act if not alive or conscious
        if (!unit.health.isAlive() || !unit.health.isConscious()) {
            // Stop any ongoing movement
            if (unit.movement.isMoving) {
                unit.movement.stop();
            }
            return;
        }

        // Find nearest enemy
        const nearestEnemy = this.findNearestEnemy(unit);
        if (!nearestEnemy) {
            // No enemies, stay idle
            return;
        }

        // Calculate distance to enemy
        const distance = this.calculateDistance(unit, nearestEnemy);

        // Decide whether to move or fight
        if (distance > this.combatRange) {
            // Too far, move toward enemy
            this.moveTowardEnemy(unit, nearestEnemy);
            unit.combat.setCombatState(false);
        }
        else {
            // In range, engage in combat
            this.engageInCombat(unit, nearestEnemy);
        }
    }

    /**
     * Sets up event listeners for attack notifications
     */
    private setupEventListeners() {
        events.on(GameEvent.attackPreparing, (data) => {
            // Only react if we're the target and can detect the attack
            if (!this.controlledUnit || data.targetId !== this.controlledUnit.id) {
                return;
            }

            // Find the attacker unit
            const attacker = this.allUnits.find(u => u.id === data.attackerId);
            if (!attacker) {
                return;
            }

            // Check if we can detect this attack based on direction and experience
            if (!this.canDetectAttackDirection(this.controlledUnit, attacker)) {
                // Attack from behind and we can't detect it
                return;
            }

            // Register the incoming attack for reaction
            this.reactionSystem.registerIncomingAttack(this.controlledUnit, attacker, this.currentTime);
        });
    }

    /**
     * Finds the nearest enemy unit
     */
    private findNearestEnemy(unit: Unit): Unit | null {
        let nearest: Unit | null = null;
        let minDistance = Infinity;

        for (const other of this.allUnits) {
            // Skip self and teammates
            if (other.id === unit.id || other.team === unit.team) {
                continue;
            }

            // Skip dead or unconscious enemies
            if (!other.health.isAlive() || !other.health.isConscious()) {
                continue;
            }

            const distance = this.calculateDistance(unit, other);
            if (distance < minDistance) {
                minDistance = distance;
                nearest = other;
            }
        }

        return nearest;
    }

    /**
     * Calculates distance between two units
     */
    private calculateDistance(unit1: Unit, unit2: Unit): number {
        return Math.sqrt(
            Math.pow(unit2.movement.x - unit1.movement.x, 2)
            + Math.pow(unit2.movement.y - unit1.movement.y, 2),
        );
    }

    /**
     * Moves unit toward enemy in both X and Y directions
     */
    private moveTowardEnemy(unit: Unit, enemy: Unit) {
        // Only issue new movement command if not already moving
        if (!unit.movement.isMoving) {
            const dx = enemy.movement.x - unit.movement.x;
            const dy = enemy.movement.y - unit.movement.y;
            const distance = Math.sqrt(dx * dx + dy * dy);

            // Move to a position just outside combat range
            const stopDistance = this.combatRange / 2;
            const ratio = (distance - stopDistance) / distance;

            const targetX = unit.movement.x + dx * ratio;
            const targetY = unit.movement.y + dy * ratio;

            unit.movement.moveTo({ x: targetX, y: targetY });
        }
    }

    /**
     * Engages in combat with enemy
     */
    private engageInCombat(unit: Unit, enemy: Unit) {
        // Set combat state
        unit.combat.setCombatState(true);

        // Check if surrounded and try to evade if needed
        const nearbyEnemies = this.getNearbyEnemies(unit);
        if (nearbyEnemies.length > 1 && !unit.movement.isMoving) {
            // Surrounded by multiple enemies, walk backwards while facing them
            const enemyCenter = this.calculateEnemyCenter(nearbyEnemies);

            // Face the center of enemies
            unit.movement.faceTowards(enemyCenter);

            // Walk backwards away from enemies (slower than normal, maintains facing)
            unit.movement.moveBackward(30); // Move back 30 pixels

            this.messages.push(`${unit.name} retreats backwards while surrounded!`);
        }
        else if (unit.movement.isMoving && nearbyEnemies.length <= 1) {
            // No longer surrounded, stop evasive movement
            unit.movement.stop();
        }

        // Attack detection is now event-based via setupEventListeners()
        // No need to poll for incoming attacks

        // Check if we need to defend - interrupt current action if necessary
        const defenseCheck = this.shouldDefend(unit);
        if (defenseCheck.defend) {
            const currentAction = unit.combat.getCurrentAction();

            // Only interrupt offensive actions, not defensive ones
            // Ripostes cannot be interrupted (uninterruptible counter-attack)
            if (currentAction && (currentAction.type === 'attack' || currentAction.type === 'heavyAttack')) {
                const interrupted = unit.combat.interruptAction();
                if (interrupted) {
                    this.messages.push(`${unit.name} cancels attack to defend!`);
                }
            }
        }

        // Make combat decision if idle
        if (unit.combat.isIdle()) {
            const action = this.decideAction(unit, enemy);
            if (action) {
                unit.combat.startAction(action, enemy);
            }
        }

        // Resolve completed actions
        this.resolveCompletedAction(unit, enemy);
    }

    /**
     * Checks if defender can detect an attack based on direction and experience
     * Returns true if attack is from front or defender is super experienced
     */
    private canDetectAttackDirection(defender: Unit, attacker: Unit): boolean {
        // Super experienced fighters (0.8+) can sense attacks from any direction
        if (defender.attributes.experience >= 0.8) {
            return true;
        }

        // Calculate vector from defender to attacker
        const dx = attacker.movement.x - defender.movement.x;
        const dy = attacker.movement.y - defender.movement.y;
        const angleToAttacker = Math.atan2(dy, dx);

        // Get defender's facing direction
        const facingDirection = defender.movement.direction;

        // Calculate angle difference (normalized to -PI to PI)
        let angleDiff = angleToAttacker - facingDirection;
        while (angleDiff > Math.PI) angleDiff -= 2 * Math.PI;
        while (angleDiff < -Math.PI) angleDiff += 2 * Math.PI;

        // Allow detection if attack is within ~120 degrees in front (60 degrees on each side)
        // Experienced fighters (0.5+) have wider detection angle (~180 degrees)
        const detectionAngle = defender.attributes.experience >= 0.5
            ? Math.PI / 2 // 90 degrees on each side (180 total)
            : Math.PI / 3; // 60 degrees on each side (120 total)

        return Math.abs(angleDiff) <= detectionAngle;
    }

    /**
     * Decides what action a unit should take
     */
    private decideAction(unit: Unit, _enemy: Unit): ActionType | null {
        // Clear old pending reactions
        this.reactionSystem.cleanup(this.currentTime);

        // Check for counter-attack opportunity after successful block
        const hasCounter = unit.combat.checkAndConsumeCounterOpportunity();
        if (hasCounter && unit.combat.canPerformAction('riposte')) {
            this.messages.push(`${unit.name} ripostes!`);
            return 'riposte';
        }

        // Check if we need to defend against incoming attack
        const defenseCheck = this.shouldDefend(unit);
        if (defenseCheck.defend) {
            // Prefer blocking (more experience-based success rate)
            // All warriors can block, but experienced ones are better at it
            if (unit.combat.canPerformAction('block')) {
                return 'block';
            }
            // Fallback to dodge if can't block
            if (unit.combat.canPerformAction('dodge') && unit.stamina.staminaPercentage > 15) {
                return 'dodge';
            }
            // Can't defend, just take the hit
            return null;
        }

        // Check if we should be defensive (low health, low stamina)
        if (this.shouldBeDefensive(unit)) {
            // Just wait/rest to recover
            return null;
        }

        // Offensive actions
        if (unit.combat.canPerformAction('attack') && unit.stamina.staminaPercentage > 10) {
            const combatEffectiveness = unit.combat.getCombatEffectiveness();

            // Use heavy attack sparingly - only for experienced fighters with resources
            if (unit.combat.canPerformAction('heavyAttack')
              && unit.stamina.staminaPercentage > 40
              && combatEffectiveness > 0.8
              && unit.attributes.experience > 0.5) { // Only veterans+ use heavy attacks
                return 'heavyAttack';
            }

            // Normal attack
            return 'attack';
        }

        // Default: idle/rest
        return null;
    }

    /**
     * Checks if unit should take defensive action
     */
    private shouldDefend(unit: Unit): { defend: true; attacker: Unit } | { defend: false } {
        const attacker = this.reactionSystem.checkReactionReady(unit, this.currentTime);
        if (attacker) {
            return { defend: true, attacker };
        }
        return { defend: false };
    }

    /**
     * Determines if unit should take defensive posture
     */
    private shouldBeDefensive(unit: Unit) {
        // Low consciousness
        if (unit.health.getConsciousness() < 50) {
            return true;
        }

        // Low stamina
        if (unit.stamina.staminaPercentage < 25) {
            return true;
        }

        // Low combat effectiveness
        if (unit.combat.getCombatEffectiveness() < 0.4) {
            return true;
        }

        // High blood loss
        if (unit.health.getBloodLoss() > 20) {
            return true;
        }

        return false;
    }

    /**
     * Resolves actions that have just completed execution phase
     */
    private resolveCompletedAction(attacker: Unit, defender: Unit) {
        const action = attacker.combat.getCurrentAction();
        if (!action) {
            return;
        }

        // Check if action just finished executing (but still in recovery)
        if (action.state === 'recovering' && action.hasExecuted) {
            // Resolve the action
            if (action.type === 'attack' || action.type === 'heavyAttack' || action.type === 'riposte') {
                const isHeavy = action.type === 'heavyAttack';
                const message = AttackResolver.resolveAttack(
                    attacker,
                    defender,
                    isHeavy,
                );
                this.messages.push(message);
            }

            // Mark as resolved (prevent double-resolution)
            action.hasExecuted = false;
        }
    }

    /**
     * Gets all nearby enemies within combat range
     */
    private getNearbyEnemies(unit: Unit): Unit[] {
        const nearbyEnemies: Unit[] = [];

        for (const other of this.allUnits) {
            // Skip self and teammates
            if (other.id === unit.id || other.team === unit.team) {
                continue;
            }

            // Skip dead or unconscious enemies
            if (!other.health.isAlive() || !other.health.isConscious()) {
                continue;
            }

            const distance = this.calculateDistance(unit, other);
            if (distance <= this.combatRange) {
                nearbyEnemies.push(other);
            }
        }

        return nearbyEnemies;
    }

    /**
     * Calculates the center position of a group of enemies
     */
    private calculateEnemyCenter(enemies: Unit[]): { x: number; y: number } {
        let sumX = 0;
        let sumY = 0;
        for (const enemy of enemies) {
            sumX += enemy.movement.x;
            sumY += enemy.movement.y;
        }
        return {
            x: sumX / enemies.length,
            y: sumY / enemies.length,
        };
    }

}
